#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Hash-MoreUtils
Version  : 0.06
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/R/RE/REHSACK/Hash-MoreUtils-0.06.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RE/REHSACK/Hash-MoreUtils-0.06.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libh/libhash-moreutils-perl/libhash-moreutils-perl_0.05-2.debian.tar.xz
Summary  : 'Provide the stuff missing in Hash::Util'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Hash-MoreUtils-man

%description
# NAME
Hash::MoreUtils - Provide the stuff missing in Hash::Util
# SYNOPSIS
use Hash::MoreUtils qw(:all);

my %h = (foo => "bar", FOO => "BAR", true => 1, false => 0);
my %s = slice \%h, qw(true false); # (true => 1, false => 0)
my %f = slice_false \%h; # (false => 0)
my %u = slice_grep { $_ =~ m/^[A-Z]/ }, \%h; # (FOO => "BAR")

my %r = safe_reverse \%h; # (bar => "foo", BAR => "FOO", 0 => "false", 1 => "true")

%package man
Summary: man components for the perl-Hash-MoreUtils package.
Group: Default

%description man
man components for the perl-Hash-MoreUtils package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Hash-MoreUtils-0.06
mkdir -p %{_topdir}/BUILD/Hash-MoreUtils-0.06/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Hash-MoreUtils-0.06/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Hash/MoreUtils.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Hash::MoreUtils.3
